### ISSUE TITLE
stretchwords freezes

### ISSUE THREAD

**Issue by narayanven** [standalone/stretchwords#1]
I played against myself and it seemed to be going well until I played a killer word and that seemed to kill the game. See attached pictures.
![20161103_195220](https://cloud.githubusercontent.com/assets/23281573/20032066/a9aa8ee8-a33f-11e6-9eaf-c546a56d52da.jpg)
![20161103_195213](https://cloud.githubusercontent.com/assets/23281573/20032067/a9aef604-a33f-11e6-8ce1-42c8d82592f7.jpg)

**Comment by narayanven** [comment]
this is weird!  i filed the report, opened my ipad and ... the game was ready to go!  not sure why it paused so long that it seemed to have frozen.

**Comment by bengottlieb** [comment]
Have you seen this happen again?

**Comment by narayanven** [comment]
no, i haven't.  i think i may have just done something stupid.  let's close this now.  will open another one if it recurs.
