### ISSUE TITLE
Buttons in the tile stage of the game

### ISSUE THREAD

**Issue by bizquig** [standalone/stretchwords#12]
Liz was confused with the <--> button....This segues to my proposed three buttons at the top of the tile screen in the game:

Undo... use the universal undo picture (the curved arrow backward). Look at every word processor and use that image

"Main menu" returns to the main menu with no change in the status of the game. Image: home

"Forfeit" ... self explanatory. You lose and the opponent wins. Game disappears from list. Image: X (clicking this opens up a dialog box confirming the decision to forfeit)

**Comment by bengottlieb** [comment]
Should we do away with the "Moves" (ie. Game History) button?

**Comment by bizquig** [comment]
Can we have it as a drag down feature? Like if you drag down from the top of the screen you see all the moves? Otherwise it's missing? A little surprise and delight maybe?

**Comment by bengottlieb** [comment]
That's a hidden feature, and would conflict with the Notification Center (try dragging from the top of your screen now)

**Comment by bizquig** [comment]
Let's skip "Moves" for now, unless it's a pain to remove and add later.

**Comment by bengottlieb** [comment]
easy. done.
