### ISSUE TITLE
Old games problems

### ISSUE THREAD

**Issue by bizquig** [standalone/stretchwords#14]
I cannot seem to start a game with Narayan. Also, I have a bunch of games that appear to be dead. Is there a way to clear all my games and start fresh?

**Comment by bengottlieb** [comment]
not ALL Your games, but you can swipe-to-delete a game. How are you trying to start the game? Can you try with me?

**Comment by bengottlieb** [comment]
What happens when you (or Narayan) taps on the "Let's Play" link?

**Comment by bizquig** [comment]
I can't start a game with NV. And you BG for that matter.

**Comment by bengottlieb** [comment]
I need details. Does it crash? Does it open? What happens?

**Comment by bizquig** [comment]
would this be easier here, with screen caps, or over phone?
