### ISSUE TITLE
strange behaviour at end of game

### ISSUE THREAD

**Issue by narayanven** [standalone/stretchwords#15]
i opened the app after updating to see that you'd played EXASPERATED and it was my turn.  i played TACTILE.  at that point the game was over so it asked me if i wanted a rematch. i think i asked for a rematch.  when i went back to the home screen, i found the game still there and it was still my turn.  when i went to the game, it seemed like it was done.  this persisted for a bit and then the game just disappeared.  it wasn't in completed games either.  

![20161122_184610](https://cloud.githubusercontent.com/assets/23281573/20549955/ab522432-b0e5-11e6-8271-422ec50b16dd.jpg)
![20161122_184618](https://cloud.githubusercontent.com/assets/23281573/20549956/ab52f326-b0e5-11e6-9507-6eb2839276e2.jpg)

**Comment by bengottlieb** [comment]
Hit that little bug icon in the lower right and see what it has to say (it means there was an error).

**Comment by narayanven** [comment]
unfortunately, the game has disappeared so i can't tell what it was.

**Comment by bengottlieb** [comment]
I think we've fixed this behavior. Please let me know if it occurs again.
