### ISSUE TITLE
Game play wish list

### ISSUE THREAD

**Issue by bizquig** [standalone/stretchwords#2]
1) running score of the word youre going to play so you can asses if it's a good move or not
2) smart interface so that if you plan on playing the word EXAMPLE and you just type XAMPL after stretching the two Es and there is a tile that has AM on it, the computer gives you that tile
3) reminder that there are three moves left, then two, then the last one

**Comment by bengottlieb** [comment]
1. That's already there, isn't it? (under the word is the value)
2. Good idea, I'll add that
3. That's there; above the word it should say "Round 1 of 5", or whatever the appropriate numbers are.

**Comment by bizquig** [comment]
Re:3 maybe a pop up or something? Would it be annoying or would it raise the stakes?

**Comment by bengottlieb** [comment]
I am definitely not a fan of popups; open to ideas, however.

**Comment by bengottlieb** [comment]
I've implemented #2.
