### ISSUE TITLE
When we have the Facebook integration... (layout notes)

### ISSUE THREAD

**Issue by bizquig** [standalone/stretchwords#22]
We don't need the name, just the face and the score. 
If it's an AI, we need a pic for Easy, Medium, Hard. Probably wouldn't hurt to have names/characters for these AIs.
The scoreboard section takes up too much space so it could be streamlined.

**Comment by bengottlieb** [comment]
We need to fit the current round, the current word, the current score (for that word) and the player info (name/image and current score).  I based this design on Jeremy's prototype, but I agree, it needs work. If you've got a better design, please lay it out and share.
