### ISSUE TITLE
Opening animation

### ISSUE THREAD

**Issue by bizquig** [standalone/stretchwords#23]
The title STRETCHWORD to my ears sounds incomplete. But we should absolutlely stretch out the title.

Three proposals:

1) You load the game and you see the Stand Alone logo for two seconds, then the name for our yet-to-be-named imprint that supposedly made Stretchwords. That name is in tiles like our game and has two Ss in it. EMBASSY GAMES or something. Stretchwords animates from the SS.
2) We get a sentence that basically says "LETS PLAY STRETCHWORDS" But the three words in that sentence are written so that the second word stretches from the first word and STRETCHWORDS stretches from the second. Obviously, we cannot stretch that sentence with my example, but you should hopefully get the ideas.
3) The screen starts off with a 4 tiles in a 2x2 array.  SH at the top, WS at the bottom. Those stretch out to STRETCH and WORDS.

No matter what, we should have other colored tiles in there.  Like S(TR)ET(CH)WORDS or something.

**Comment by bengottlieb** [comment]
We want to make the intro as short as possible. I am strongly opposed to needless logo displays; I'm still not sold on the current animation. I am, however, open to different combinations of letters/words. I think it would make sense for you to sketch out a design you think would be good; I'm personally a fan of simplicity (hence the single stretched word).

**Comment by bizquig** [comment]
I just looked at 6 games and the intro to all of them was immediate. A static image mostly and then right to the game. I'm rethinking that even stretching out STRETCHWORDS might be too long. 

Can we just make it a static image (for now until we get a designer) that uses the tiles like so? 

S(TR)ET(CH)WO(RD)S

(The parentheses are bigrams)
