### ISSUE TITLE
There's no reason to have the names both underneath the icon and underneath the tiles, see below. We should just have the score is underneath the tiles.

### ISSUE THREAD

**Issue by bizquig** [standalone/stretchwords#26]
There's no reason to have the names both underneath the icon and underneath the tiles, see below. We should just have the score is underneath the tiles.
![img_0119](https://cloud.githubusercontent.com/assets/23285201/21010304/56ffe8a2-bd19-11e6-8bf8-b1769687db59.PNG)

**Comment by bengottlieb** [comment]
fixed
