### ISSUE TITLE
Stats

### ISSUE THREAD

**Issue by bizquig** [standalone/stretchwords#29]
Stats should include:

1. Wins/Losses
2. Rank among friends
3. Highest score
4. Highest word and score

Here's how Two Dots does a leader board ... and a rough back of the envelope sketch (first pass) of how ours might look.

![statssketch](https://cloud.githubusercontent.com/assets/23285201/22428002/58d7ffdc-e6d3-11e6-9cf6-faed852a1940.jpg)
![twodots](https://cloud.githubusercontent.com/assets/23285201/22428023/7923f520-e6d3-11e6-81a4-0aa477bd60e4.png)

**Comment by narayanven** [comment]
how about using the ELO system?

**Comment by bengottlieb** [comment]
Electric Light Orchestra?

**Comment by narayanven** [comment]
https://en.wikipedia.org/wiki/Elo_rating_system
