### ISSUE TITLE
Need various bonuses for actions in Single Player mode

### ISSUE THREAD

**Issue by bengottlieb** [standalone/stretchwords#30]

**Comment by bizquig** [comment]
1. Tiles begin with 2, then 3, 4, 5, 6, 6 forever.
2. Player gets 30 seconds bonus upon using all tiles
3. Players get 30 seconds for every 100 points? (This might be too high)
4. We need to keep a stat of highest score.

**Comment by bengottlieb** [comment]
done. Tracking both highest score and most number of words.
