### ISSUE TITLE
Dupes

### ISSUE THREAD

**Issue by bizquig** [standalone/stretchwords#39]
If a player attempts to play a word already played, the computer should have a message saying that it's an illegal move.

**Comment by bengottlieb** [comment]
Right now we enable the play button if it's a legal word, and disable it otherwise. Should we enable it for dupes, but then show a message?

**Comment by bizquig** [comment]
I can't imagine dupes are a problem now the way the game is. It's changed so much from the earlier iterations where dupes were a much larger problem.

**Comment by bengottlieb** [comment]
okay, I'll close this.
