### ISSUE TITLE
no notification when opponent plays

### ISSUE THREAD

**Issue by narayanven** [standalone/stretchwords#4]
brendan and i played a game.  i invited him.  he played the first word.  he was notified when i responded but i didn't get anything when he played.  when i refreshed the "Matches" screen, i could see that he had played.  is it because i'm on version 9.3?

**Comment by bengottlieb** [comment]
iCloud notifications seem to be a little hit-or-miss. I'm trying to figure out if this is something we're doing, or if it's a systemic issue.
