### ISSUE TITLE
AI Rules

### ISSUE THREAD

**Issue by bengottlieb** [standalone/stretchwords#41]

**Comment by bizquig** [comment]
https://docs.google.com/document/d/1f_xwjwhcjn0zdW7CGUN9uObSp763UNXN6AM1hXfJ5Yw/edit?usp=sharing

**Comment by bengottlieb** [comment]
I've implemented an ELO ranking system. I think we may want to re-visit our current word ranking, however. Right now it's 0-100, with rarer words being lower value. This means, as we play harder words, our rank goes down. Also, I'm adjusting the player's rank more in response to harder words played, and less for easier ones (so their rank primarily goes in one direction). Since we're using the rank to set the level of the AI player, this seems to make sense. Finally, I'm starting players out at a rank of 70.
