### ISSUE TITLE
Add random player feature

### ISSUE THREAD

**Issue by bengottlieb** [standalone/stretchwords#57]
We need to figure out the UI for this; the code is already in there.

**Comment by bengottlieb** [comment]
We need discuss with the artist; what's the user experience for this?

**Comment by bengottlieb** [comment]
Jenny, do you have any ideas here? We want to be able to say something like "Start a game with a random player", and have the server play matchmaker to find someone else looking for a match. Not sure where we can put this in the UI, however.

**Comment by JennyRobatto** [comment]
Done. I will send you a pdf to look at today. I'm making a lot of changes on the UI.
