### ISSUE TITLE
game stuck because brendan played a word that doesn't show up on my device

### ISSUE THREAD

**Issue by narayanven** [standalone/stretchwords#6]
i started a game and played SYLLOGISM.  brendan says he played SNAZZY and has been waiting for me to play.  meanwhile, my screen shows that it is my turn but when open that game it is grayed out and still shows as if he hasn't played.  

besides fixing this bug, can we also have a way of killing a game so that we don't get stuck like this?  thanks!

![20161113_101118](https://cloud.githubusercontent.com/assets/23281573/20247874/bdf95dd6-a98c-11e6-83ed-81202b32ec3e.jpg)
![20161113_101055](https://cloud.githubusercontent.com/assets/23281573/20247875/c28551ac-a98c-11e6-8b8e-2d1f6b15c75a.jpg)

**Comment by bengottlieb** [comment]
If I understand your screen shots, you're seeing "BEQ's turn" in game, but when you view the list of matches, it says it's your turn. Is that correct?

**Comment by narayanven** [comment]
yes.
beq says he played his turn so it is my turn but i don't see the SNAZZY he played to my SYLLOGISM. 

```
On Sunday, November 13, 2016 11:06 AM, Ben Gottlieb <notifications@github.com> wrote:
```

 If I understand your screen shots, you're seeing "BEQ's turn" in game, but when you view the list of matches, it says it's your turn. Is that correct?—

**Comment by bengottlieb** [comment]
if you pull to refresh in the Matches list, or tap the score in the Match, does it update? (do you see the spinner start in the upper left corner for a moment when you do that?)

**Comment by narayanven** [comment]
WHAT?!!  tapping the score did it.  but why?! 

```
On Sunday, November 13, 2016 12:13 PM, Ben Gottlieb <notifications@github.com> wrote:
```

 if you pull to refresh in the Matches list, or tap the score in the Match, does it update? (do you see the spinner start in the upper left corner for a moment when you do that?)—

**Comment by bengottlieb** [comment]
I'm guessing I need to be more aggressive in updating the game state. I'm currently re-building the game play screen; when that's done, I can look at this as well.

**Comment by bengottlieb** [comment]
This should be fixed in tonight's build.
