### ISSUE TITLE
New game layout questions

### ISSUE THREAD

**Issue by bizquig** [standalone/stretchwords#61]
If you play a long word, the player's avatar is pushed off the screen. Should we move the word that is being played down a bit?

Also, that GO button feels unnecessary.

**Comment by bengottlieb** [comment]
Which go button? The one on the keyboard, or the big yellow one?

**Comment by bizquig** [comment]
The one underneath the keyboard.

**Comment by bengottlieb** [comment]
Still unclear. What color?

**Comment by bizquig** [comment]
It appears this has been fixed in the new build. Not in the timed challenge though.

**Comment by bengottlieb** [comment]
fixed now.
