### ISSUE TITLE
Match Ended notifications need work

### ISSUE THREAD

**Issue by bengottlieb** [standalone/stretchwords#73]
I think he actually won the match, but certainly the text is incomplete.

![img_0239](https://user-images.githubusercontent.com/53162/34970566-a5b673c6-fa3a-11e7-82de-18dca1785d45.PNG)

**Comment by glennturner** [comment]
My guess is: the user has no display name in which case, there's not much I can do. (I'd suggest that the client request a display name from the user.)

However, without specific match info (please note whether it's prod/dev), I can't troubleshoot it further.

**Comment by bengottlieb** [comment]
It was prod, and we've been getting move notifications for the game back and forth, so I don't think that was it. I will try to figure out which match it was.

**Comment by glennturner** [comment]
Yeah, the only non-display_name users on prod are my admin and manual test accounts, so it's possible that it was fired without a winner. If you get me the match ID, I can investigate it further.

**Comment by glennturner** [comment]
Do you want to receive abandoned game alerts?

**Comment by bengottlieb** [comment]
Is the prod admin up and running? Abandoned game alerts: not right now, might want them in the future.
