### ISSUE TITLE
Can we link chats to Players as well as individual matches? 

### ISSUE THREAD

**Issue by bengottlieb** [standalone/stretchwords#76]
ie, can I have a chat that's with a player, instead of only linked to a particular match?

**Comment by glennturner** [comment]
No, SAGS was set up for match-based conversations only. Revising that would be a very heavy lift.

**Comment by glennturner** [comment]
I'd also argue that anything that -isn't- game/match-centric is not in the interest of the purposes of SAGS. Users can DM in all sorts of other ways.

**Comment by bengottlieb** [comment]
The thinking behind this is: you start a convo in a match, the match ends, and you create a new match with the same player; you probably want to continue the conversation, no?

**Comment by glennturner** [comment]
Yes, we discussed this before. This is why we have the rematches, so you can pull prior conversations from parent/child_rematch.

**Comment by bengottlieb** [comment]
I think we're going to have to revisit this. If we want to shift to a purely player-based model (where there are NO chat-based convos) I'm okay with that, but after some testing, what we've currently got is not sufficient. Let's figure out the simplest way to implement the change.

**Comment by glennturner** [comment]
The entire SAGS system was built around conversations being married to matches. There is no simple way to implement this.

**Comment by bengottlieb** [comment]
implemented.
