### ISSUE TITLE
UI rehaul

### ISSUE THREAD

**Issue by bizquig** [standalone/stretchwords#9]
The game constantly will return to a landing page.

That landing page will have your icon, name. 
Clicking on the icon will pull up stats (win-loss-tie, highest score, flair, etc.)

Top section will have a button that reads "New Game"
That will launch the window that we currently have (number of moves, tiles, ... choose a live opponent or AI and then the AI's difficulty, etc.)
Middle section is labeled "Your Move"
Each of those entries will be the word that your opponent played, and their name. Maybe even the score 
Bottom section is labeled "Their Move"
These are all the words you've played and are waiting for opponent's moves.

We will return to this window after every move in a turn-based live opponent game, or when you are no longer interested in playing the AI.

**Comment by bengottlieb** [comment]
new Landing Page implemented.

**Comment by bizquig** [comment]
Completed matches looks a little cluttered. If we need it for testing purposes fine, but let's put it on a different page. Otherwise, I don't think it's necessary. 

The transition between games is very smooth. Could have *something* else to signal we're going to a new page. Some animation, perhaps? I'm wondering if nows the time to bring in sound?

**Comment by bizquig** [comment]
Can this be closed?
