### ISSUE TITLE
Swap problem?

### ISSUE THREAD

**Issue by bizquig** [standalone/stretchwords#92]
What happens when you "swap"? I just did it and it gave me a new word, but then I went back to the home screen thinking I would lose a turn. But it still says it's my turn and when I go back into the game it's not the new (swapped) word and "swap" is greyed out. Oh wait. Did I lose points for that? Looks like I lost points. Okay. If I had just stayed there, I guess I would have played with the new word instead of the old word. Got it.

**Comment by bengottlieb** [comment]
okay, swaps are now handled better. They're remembered between launches and devices, and shown in the list appropriately
